### ISSUE TITLE
Question about the  fusion package

### ISSUE THREAD

**Issue by LZL-CS** [TencentYoutuResearch/NeRF-Loc#1]
Hi, thanks for sharing your excellent work. When I try to run 'preprocess_7Scenes', I am confused about where is 'import fusion' package:
https://github.com/TencentYoutuResearch/NeRF-Loc/blob/dc3edcc927644bf948d966cf36766ef034182b69/datasets/video/preprocess_7scenes.py#L20

I appreciate any help you can provide.

**Comment by JenningsL** [comment]
Sorry about the missing file, you can find it here https://github.com/andyzeng/tsdf-fusion-python/blob/master/fusion.py

**Comment by LZL-CS** [comment]
ok, thanks for your reply!

**Comment by LZL-CS** [comment]
Hi @JenningsL, similar issue about the missed package "**_models.ibrnet.ibrnet_**": 
https://github.com/TencentYoutuResearch/NeRF-Loc/blob/dc3edcc927644bf948d966cf36766ef034182b69/models/conditional_nerf/multiview_aggregator.py#L15

**Comment by JenningsL** [comment]
Please checkout this repo https://github.com/JenningsL/nerf-loc,  where some dependency issues are fixed. Unfortunately, I don't have time to test the code thoroughly. So you can try it out and let me know if other problem exist.

**Comment by LZL-CS** [comment]
ok and hanks for you reply!

**Comment by LZL-CS** [comment]
Here, I don't know where is the **"from .superpoint import SuperPoint"**. Other missing file problems are also mentioned in the issues put forward by others, we hope you have time to fix them so that we can follow your work further, thanks!

https://github.com/JenningsL/nerf-loc/blob/c12111a73f71c21e3bd3c0f0b6dc26f23cc183be/nerf_loc/models/pose_optimizer.py#L18
