### ISSUE TITLE
Question about trhe missed packages

### ISSUE THREAD

**Issue by LZL-CS** [TencentYoutuResearch/NeRF-Loc#8]
Hi @JenningsL, I don't know where the "from .superpoint import SuperPoint" is. Other missing file problems are also mentioned in the issues put forward by others, and we hope you have time to fix them so we can follow your work further. Thanks!

https://github.com/JenningsL/nerf-loc/blob/c12111a73f71c21e3bd3c0f0b6dc26f23cc183be/nerf_loc/models/pose_optimizer.py#L18

**Comment by JenningsL** [comment]
Please refer to [this](https://github.com/TencentYoutuResearch/NeRF-Loc/issues/6).
